[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  RUBY_VERSION = "2.7.2"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
